import 'package:flutter/material.dart';

class QuarterProvider extends ChangeNotifier{
  final List<String> city=['DOUALA', 'YAOUNDE'];
  final List<String> quarterDouala = [
    "AKWA",
    "AKWA BONAMOUTI",
    "AKWA EMILIE SAKER",
    "AKWA NORD",
    "AKWA NORD PADRE PIO",
    "AKWA NORD TERMINUS",
    "AKWA SOCAR",
    "AXE-LOURD DLA-YDE",
    "BALI",
    "BALI ENTRELEC",
    "BALI RUE DE LA JOIE",
    "BANGUE",
    "BASE ELF",
    "BASE NAVALE",
    "BASSA",
    "BASSA Z.I",
    "BASSA-CCC",
    "BEEDI",
    "BEPANDA",
    "BEPANDA AXE-LOURD",
    "BEPANDA TONNERRE",
    "BESSENGUE",
    "BEPENDA-OMNISPORT",
    "BONABASSEM",
    "BONABERI",
    "BONABERI BEKOKO",
    "BONABERI BOJONGO",
    "BONABERI BONASSAMA",
    "BONABERI MABANDA",
    "BONABERI SODIKO",
    "BONADIBONG",
    "BONAMOUSSADI",
    "BONAMOUSSADI DENVER",
    "BONAMOUSSADI SANTA BARBARA",
    "BONANJO",
    "BONAPRISO",
    "BONAPRISO ARMEE DE L'AIR",
    "BONAPRISO BONADOUMAHOME",
    "BONAPRISO CHOCOCHO",
    "BONAPRISO CIMETIERE",
    "BONAPRISO HYDROCARBURES",
    "BONAPRISO MARCHE DES FLEURS",
    "BONAPRISO RUE KOLOKO",
    "BONAPRISO RUE NJO NJO",
    "BONAPRISO USINE BRASSERIES",
    "BONATEKI",
    "BONATONE",
    "BORNE 10",
    "BRAZZAVILLE",
    "CAMP YABASSI",
    "CITE-CICAM",
    "CITE-PALMIERS",
    "CITE-SIC",
    "DAKAR",
    "DEIDO",
    "DEIDO COAF",
    "DEIDO ECOLE PUBLIQUE",
    "DEIDO FEU ROUGE",
    "DEIDO GRAND-MOULIN",
    "ESSEC",
    "JAPOMA",
    "KM5-TERMINUS",
    "KOTTO",
    "KOTTO BLOC",
    "KOTTO IMMEUBLE",
    "KOTTO VILLAGE",
    "LENDI",
    "LOGBABA",
    "LOGBESSOU",
    "LOGPOM",
    "MADAGASCAR",
    "MAKEPE",
    "MAKEPE BM",
    "MAKEPE COURS SUPREME",
    "MAKEPE LYCEE",
    "MAKEPE PETIT PAYS",
    "MAKEPE ST TROPEZ",
    "MAKEPE MISSOKE",
    "MARCHE CONGO",
    "MBANYA",
    "SABLE",
    "MBOPPI",
    "NDOGBONG",
    "NDOGPASSI 1",
    "NDOGPASSI 2",
    "NDOGPASSI 3",
    "NDOGSIMBI",
    "NDOKOTTI",
    "NEW-BELL",
    "NEW BELL CIMETIERE",
    "NEW BELL KASSALAFAM",
    "NEW BELL LYCEE",
    "NEW BELL MARCHE CENTRAL",
    "NEW BELL NKOLOULON",
    "NEW DEIDO",
    "NKONGMONDO",
    "NKOULOULOUN",
    "NYALLA",
    "PK8",
    "PK9",
    "PK10",
    "PK11",
    "PK12",
    "PK13",
    "PK14",
    "PK15",
    "PK16",
    "PK17",
    "PK18",
    "PK19",
    "PK20",
    "PK21",
    "PK22",
    "PK23",
    "PK24",
    "PK25",
    "ROND-POINT DEIDO",
    "VILLAGE",
    "YASSA",
    "YOUPWE",
  ];

  final List<String> quarterYaounde=[
    "ABANG",
    "ABATTOIR",
    "AKONO",
    "AHALA2",
    "AHALA BARRIERE",
    "ANGUISSA",
    "AYENE",
    "AWAE",
    "BIYEM-ASSI",
    "BITENG",
    "BITOL",
    "CAMWATER",
    "CARREFOUR ETOA MEKI",
    "CENTRAL MEFOU",
    "CMC",
    "DIBANG",
    "DZENG",
    "EFOULAN",
    "EKOUNOU",
    "ELIG ESSONO",
    "ELIG EDZOA",
    "ESSOS",
    "FIBOT",
    "FOUDA",
    "FOUGEROL",
    "INGENIEURIE FORESTIERE",
    "INSTITUT SAMBA",
    "KIKOT",
    "KOMEKUI",
    "KONDENGUI",
    "LADA",
    "LOLODORF",
    "MAKAK",
    "MANGUIER",
    "MBANDJOCK",
    "MEFOUN",
    "MELEN",
    "MIMBOMAN",
    "MESSASSI",
    "MVAN",
    "MVOGADA",
    "NGOA EKELE",
    "NGOUMOU",
    "NGOUSSO",
    "NKOLBISSON",
    "NKOLEWOUE",
    "NKOMO",
    "NLONGKAK",
    "NSAM",
    "OBALA",
    "OLEMBE",
    "OMNISPORT",
    "ODZA",
    "OYOMABAN",
    "SA'A",
    "SOA",
    "SIMBOCK",
    "TROPICANA",
    "TSINGA",
  ];
  List<String> get cities{
    return [...city];
  }
  getQuarter(String city){
   if(city == 'douala'){
     return quarterDouala;
   }if(city == 'yaounde'){
     return quarterYaounde;
   }
   notifyListeners();
  }
}